### ISSUE TITLE
Test the Cupcake app: Android Basics in Compose

### ISSUE THREAD

**Issue by TimMerker** [google-developer-training/basic-android-kotlin-compose-training-cupcake#29]
When checking out main and running all the tests from CupcakeScreenNavigationtest I get the following exception for every test:

12-25 15:39:20.491 24678 24705 E TestRunner: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.cupcake.test/androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?

Does anybody have the same problem? I just checked it out and didn't change anything.

**Comment by wseubert** [comment]
I have the same issue.   Did you solve yours ?

**Comment by txcxjp** [comment]
Adding
```
    androidTestImplementation "androidx.test:core:1.5.0"
```
to build.gradle worked for me.

Reffering
- https://issuetracker.google.com/issues/240993946  

and links from this.

**Comment by johnshea** [comment]
Hi @TimMerker @wseubert 

Thank you for writing in with your issue.

I was unable to duplicate your issue using the latest version of Android Studio and the latest code on branch `main`.

If you have time, please update your version of Android Studio and use the latest code in branch `main` and see if you are able to duplicate this issue.

If are still experiencing an error, open a new issue and provide as much details as possible and screenshots so that we can try and duplicate it too. We would need what version of Android Studio you are running, operating system, etc.

Thank you in advance for your help.

Hope you are enjoying the course!

Regards.
